---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: music-collector-db-secret
  namespace: music-collector-staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgASnQqMVsr+S6+Q7Xd5SiWSzdPN0iI+q/k7IxiMkLZvpbACA8DoWvRZqJb97PkjM3qt2N2G4kcnjw091fqTPwmDf9fVnKnXMQtR2aFpBIstdodjo+Sxf2BLa90LEzGb5x74/52k+tE6pKApjHCoVzagNZwwtCa32uAYINKDz9SiL72V6M+PbpiAwfxnyAold9yjsZTolhCDhSI9KL01/A3f7rYgCElkvoAc5nmy1U1wAhh/MVDBwAQIXz/er6zaOwviCTE3ocXYATnvFwrhC4udQHtDY7I424xlkMIat+9k/hP/Hgc/HNj/xmyNcZRMjc4rGJOE5Gl7gck0u+wqhV8gzOHHTHV7fFer8inW9PgwQBtIvyuE8w5Wo+avK/G5hvpd3FlmeFM8CuTwCwxIUiAPzKzxmyn6/kDvqN+4DH2nGiqDBARFI93H5CRMgcp/GJaaeiZ2j9dB3BXzX0TC7tnZRQ5N1Yi3Mw5niUZ3sqLWpdgfqskCKoYLfxRIhHr64hy2acOPvEMdf81joLdKoLqgMsvshDWFhc69s4ZBbVa1ohgPq1q1uIZ3IlhmkUEGvTJlellxBc1k3qYuu+bLvjt7jvXE/py0OKVoFpK+Paos18UMzsP+6UIU6F+xoKAEjyykRyust8pmwsIIe5MdQHXQqD0X0IiUHBmj4Yo/al+5pE1e0IVQ8hVbI82Wz41UBboR1DIB4RRV7XSc/cM0yB5EV5JaaC++9LUNHr1xpA==
  template:
    metadata:
      name: music-collector-db-secret
      namespace: music-collector-staging
