---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: music-collector-discogs-secret
  namespace: music-collector-staging
spec:
  encryptedData:
    MC_DISCOGS_TOKEN: AgBWHji302xeb5FEIvn5ELxuxLWA3CB23IRWt8yS1257RbWoX5MNbXqrp5+uo86i7UUbY2k7aJWQv1L0f+cMkluwMCf/UDrhiIgC6NJ6Du8Z3giDaUxNK06rr17nvQIK7oemdMqLJ2cDn77WHqxRikE3yfIJBVkRHibsQFrr4oh+RE62W0LNejmZgP6nnxkbpAHASDosPPIMQ9tsImw9ZGTr9+nwfFWT/Ev3kIfWaGDgMoVNJ1sJpJN0HnkEyERFBJ/VkAH5A8IUk5m9e4ae5Bf3KvZs9GZEf8zT4dhXi4vILd6TIou2wwczUmPaZ+46bW9kYThm1NQb05ex0BiH+C7XpgbPEqYCCMkHcbGKaqjl0L9In0I91SnkQK+LvmxpSqaO5Bm4TuYVFYRdaDiBnBuMQb9HyRXw5ddeaxayPabdnNYZWytm05Zup28XbFnx8bfugkq+F6+QOWZ2hHmeezbMJluYBZo7LaPa3UVNFsArVrTu4pRS1cTLNS0C529k3SiAumYEk0KJs7AvpkNSTTwqNJsabAcBwq+g/STWQ3i9AYlDZ52nRkBF35Dc/rOygdYUyDNzZTuR8TZczy/KoQHK9mNCPg9FbozDnKUoTuwf5ST6Zm8IwEWrmPdWSQ7GXIOOe1CcQLvFfXiOfBvxRiLpeq5vQ5cmYgIGLie1X96JRknoGSOA440G2wWm+GLP85Grviu/jqbnhSku22PgsfHQNoSUI9vNC/gGuu8z/mxjwkFS/TycdPlB
  template:
    metadata:
      name: music-collector-discogs-secret
      namespace: music-collector-staging
