---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: music-collector-mail-secret
  namespace: music-collector-staging
spec:
  encryptedData:
    MC_MAIL_API_KEY: AgC1JLBFsIVaHUQ4cAzypqHckd9zpAWem6xSY+mJ7k+ZdHcJyA/E+7qHW8Mk78STbtjrbGQCWfkFpaNJ1kQ2kS1l4GZrHLKjhjx4uOF3wBcSN3vWSJFHNTetWDl69uq3ln8Ho9zn6nnMGgrJCVQzNbYh4iIu5GHmH9XK/j37l9BE4vcWFcBMgbtbRWBSdq4oyy6psW04TDnhpCbSMGiiQ5vYX5usBGLln87Ng7Lm9vwsSuqRLV8Gx5F/qnz0MQ6pve7Smh7EBzd3UW2PgTHFW5sfwZJwIhqe64Feomtf8BzeaynZ3E/T8x03MMcGXQ7ZcAoz4ROnXHjYuDMxt+RDFaVuNSKCY0zcyOYqUmxd5luPoG2pm7ywtM2BynbTPAd1yblkpYVmNvV8UaamGSN4faYgkMIh9sGi2ssNSBlr6ImM9EH7z/3FzENMIBsCJ0Yc/45XmrRY9MdimCUC6MNx55Uk4MhxgzYZnmnrmF+zpIjatqdBlGKCZMB/MszjYEkDDAyvlg/hIufU2cCc7sqKxxGZYvzSU2l7Jsu+ykFUUYFSvhpq2lG75vplPHoBN3Tm2wywN+44OhS1Yq5GP5xDDS1G3xUTTfzPh1DilJyeon9ejKbHtG5MlLegZZi5Rl7m+/b1/BKrMCewQO6lMCjvEMR/mV1A8tt7T/P6jN4AkeJ/Fh7BFKOf4LDYjehSQ5SKA6WqqSmFwjjMQSB7r8CMbu10N5exPBFIkV+s6iuLWJvlV1zbTDNnFzyjO5Uv2u2tW46glQkHz4Iqq2Ig6mf+JKlZxviIMD0m8HRpLHu5R2uqOgGlYQ==
  template:
    metadata:
      name: music-collector-mail-secret
      namespace: music-collector-staging
