---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: music-collector-jwt-secret
  namespace: music-collector-staging
spec:
  encryptedData:
    MC_JWT_SECRET: AgBDdDi+AiQD+7/BUVd98ebIu8Z0iSSgkYTQFTEewOWK4roHdimtRHu8WW4XEWRxAU371MeNgiL1XS+ZuEaOPz8X7AzKVNJ1uNV6w8/fBZ7L5sSndx6SZ+RQSgUy8fk8e37AITF+bJSRIA+AWVJIUyaItXJvAe1MDPUqduGwT+3Kz0iFuMehCzbBCGdN24WgzH1U//8mpR2r7HW4gGokZULOVEQa3N0u8pxhbHxhW2ybTwh7+Ug0ugGXaBcBiZySMXrXWFcqW1pI/uvJIhXoIJL5nnHDqRuR/U7X8lNrdJeCuH8bDUgjK3PWX8KGwlTklJyIRb+PxtGa+S4AjiXaPM1x0qWxQKMX9cTHEmtJcnsrMNFk7pq2EhL3oCV75yknpm2VfrY+QVLo4XXa4fXTFwuyTjq72ADiFd0y/fFtdDFk/YR97BSKgh1SyySerz57/xDtmbXOARiL0UccbBOlxv5ZqEv3moOHQzcn8tB9zbvyaTm1UkXe91yFWcKNAodIGmlJIP25Mbps7uNSilM0TtPepVbRAACTjsuLJRWjF7J45/jhtICYDtYAIsGpsLxsTSa8/TlFv6RYlXB7GRgnlYg1bRpnfPQ485HsZWCQ6ECCOJRVCUWn3LJCQK0l03YBjET4tt9mu7tyvf/jvASbsCdK0kSum3brFQE57BW+rk8f250KdHDCgOOXVBB+hpgRAmLoIcJEoX5QeUP4/hxuWEQsVPaA2Zndv+zUhUGt3X7e34ziePQtWH4vea19Y6rXXbJheYUvqzKHI3IZP4EJTZ/V
  template:
    metadata:
      name: music-collector-jwt-secret
      namespace: music-collector-staging
