---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: music-collector-db-secret
  namespace: music-collector-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAR86ad3tpQdpEeboq/fQSdVkvtdCu6p+M6QsE9sPu7WoiTWE6xoRHrwvIwvogYrS7wG4T8NlR5Sn6gBjV7+2gxb7Yi/Hc2P5TSj8apM2+py42hlWfwWS3zySmgISPSSAY3oGpeu8aXxLpL3tijTz9F9TiZDrtgcPKGbtb4KCEYMj8rgwebMGUewHknvr8Pfr0jZZF5YG1Qsyk+HAr1l6zqw5bbXvVbGAVjXv7+RWZks5zMKda/ooe+IL5EW03RfuZ+C+GIVO8FwjxNm0HWCqDBdM17lb24crUZ/KS45NxQOaU1fyBQ2stbIX8s7/zy+focS70KJ7zpWkhTcN3xbNXpvY1TALoeXA/QGTjsxpJNm71ewoG3daXHNGXFehj9XLL522h/rkCpgT6Vfol1ErFiI8NAvJdg7VgNJZS7nS7P9wIzWnGG6drZr4KUkmKSH++mrsAgWKF0oB7ohmtDnaOSnUGiekh/TzJnCwePIgWWPcUrq9A2wsKwryWqid1eGjrLeu3vULU3U4C1gTCUtItFEa6U+Ckd3gqp0OztxpiFGuZopql/QB2n0TI0hgdXEzD4zZV7GYEumijoQqBEJOXKOOGPn4FIwA+ka6Bv4En1WytLi6RBoRFKVl1hrIqPQ4KCM7e4MafZDLkjKR7zv0l296MciodNRYnDIN7CcIsiTV2q1qCg65+kXm2PB3jsMdM56jYKArRizL9Kb23+FfVPwBy6/wtqQNhVUOKofx4GDQ==
  template:
    metadata:
      name: music-collector-db-secret
      namespace: music-collector-prod
