---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: music-collector-mail-secret
  namespace: music-collector-prod
spec:
  encryptedData:
    MC_MAIL_API_KEY: AgAxLzH3UC29v7uGG8URENga99bBPe8De8tKzjNDcQj+bZ355RIs1B55pRdPJS0Rk6yq6s37je3EoAirME/5JvRlCuprBh+2a5p1/tW5PTzG3FZJt5cD7VjAUTbY787a4Azi2IvxgDrl1j1lYCTgcR57CPOtNdKomf+cMWRC8uoqZLpKyP+zTCkXBEtLwuQgxC5Q+hMBZd1Eo+Ns/BkRC8BJvG56z2wrtV0AiLtNuu60I+uyzTEChn9tatlEqhopnCvAZFyB0djxOYIm9lFdjsnW3Q3jVH2RMdwTohJQYnj53O6W9qW4AMsXb7D+S4591x+2gAzTqyb34WNfASMPnM4uk22GAEGUNV0iCaAddfyTi2SjPqF6asAmPc5RdU3d2XylDnBErba8nmFG4bdKazSO67aUGgo/lpiYee+mFJT+7V5ORQ31zQVHk2AbwqHOdQzlph07gWLEul5eHmc1KYHcT6LGtPMoRVWwIrFC+QVcStqfo5tG2cPbHRe04qZf6Hc2IpDzWjtAs7BEh2/65ZL4/ukvh+51lvKNIC3oXjCQS4hz57JUmMR0ivg9ZsbyUf9E4In0AEJ3NGH8B2ssnu9w14KK5OrzQJ0vMggAh/dHB8uCARWEzJcNi7tWrDvERMTv3HHJEQt2k885s4L21NUKmzGbx6jpM1Fg8RCg9bHKbo7XEh7QTdvtl9AFiAWNgsAXuTjJllXGXTveR1BDs1tipKPM0afaTxsBUT9vr8lfuX/GW5+7H+3tB37PeS+sPCR2AIM5+JzyL+TYkr6KNliTyYTEzCy67wVU4e28C3S2el8A3A==
  template:
    metadata:
      name: music-collector-mail-secret
      namespace: music-collector-prod
