---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: music-collector-jwt-secret
  namespace: music-collector-prod
spec:
  encryptedData:
    MC_JWT_SECRET: AgDQ1h3bejk4wuJ2pUrDn2xn5Yr/K+yqTcDL2R7rys+O0TT5iHm+nV8VQqr548VWcBEligy2tdwA4M9Pwxkqm+lSlP+DhLp0L6xDn5+KRsCe4arbOpNtZcWDlJ8F6H14TLS9WdFGGU568nv07ahj/SFGMC54yRVcrDr1gHFBYprwJT1K75Iv7+DoMZtYgqsfMCDAVbjyNaUFOo9Ahvoq12YLy0gMR4Vx3hrNWMvH+bZyNHEeLWqGTpesx4A68+GIqLYRSG2tGwppjqg+S3G9dku7dJJvbwxnwkRR7wtkCNdywjrHx2iAd92IVVYjQxR0DStJ/rrvkTEnp2c6FZWho4s5DTtldXY6q+ASw3jnCpewI+nl47p+LjQOTWHtjngPcTEqHEwcCTMqlKPRypRzvM0hLF4vMmmC/eFQVVA3S8fysMBWvulQVzeosO62y6K6xBR26QrTXUyMphlsMnRYIFyACQ3jdQSNXyXizqEb4BkNEv322yXYh5T7fe4+irut8SmhXADVb/s99pCA17hs0Zud4S8gWNUDuYGH2qH1EhnzvTPexW3zIYqfaNIjvL4kFryKGiQjHHAOhW+HGCs0guQYdfmYXkgFWvJL7pmT7U6ER9aNk0olfO3O2Y/37l3w0qr/TTEEo3FwLibE3rR6wOuo0O0qGdLsakSYuWjV5d8YE8sZ4zxvV9GnTE5CZ2ecvm+EiY2qEfv1rzoM+S/Lk70Uzwxjz68Allli2wUxKi2VH2uXd98e6H379lz2VgSXu4bwkk8dWFJ3K09ug0Jrc+ls
  template:
    metadata:
      name: music-collector-jwt-secret
      namespace: music-collector-prod
