---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: music-collector-discogs-secret
  namespace: music-collector-prod
spec:
  encryptedData:
    MC_DISCOGS_TOKEN: AgAZlA3XXNHDldOqUz9qDZXXoXKe5yM0kbjRTd0AB9+MtCTXpztbL6wwDYBIP3sY+L7f1V0XRRAGuAQQoDgtmeXyQBggzjSQIo22r7jZ2qwJiewpyL2xbakBsfUCbqfEx8BU0WjrLz9zqG2HOqxgYknVVvyyYcUIxN1Zib3gpLzpWAeOL7ax97jSA6cqChvFBDeYlA3LBBNAzawti/nP3PvlKBsGpVkDkQeGV/V5AaBCMCraLlyp4Jjpra4lkoiloezHUgtWcCIJVnyeUQ137s+G0aVk1n711qMWS7D+R/vpKL9Vql3VMmlwDAFW5dnq4qGCn/HjSIrmxTNv0crpRK276pGnt1TBEGGDJYtlyUnb2icaxpP0Q7hlFMSQqym8rSt6v66AexKJA3miU76cvDRSYoAd4MoScre4qxFmwzgtkzF5H2KFiNgj7LH2XwPs8oDHxe7TdUWAmIJbuTMCmPRQ3mVMuzCLVKj54nm9RWhV2AU9zbEFxj5DddIX/uF6IBQoFOyNhn+2nY5COv65U7bY8jC4OCmfgBwrnxH+dUSKIOQ6Fiil+sZilpAWjgsTwV1gXY0PkmIO/cFlfIUwg6fC1TDlWMMHfVL3+nuovBuOYO+VsJpxbx98YaaRknrL5Stot93rivLrCv/j3VQMvjHxfXxBjKRafiWJPtsf+1FFvW3TaGrFZ9yX42PbRvnDQFHldg7HxoqC8X7zlyAwTBikSBEszKK9eR+E68BiacEhfy4iWNRaJKTp
  template:
    metadata:
      name: music-collector-discogs-secret
      namespace: music-collector-prod
